apiVersion: v1
kind: Pod
metadata:
  name: local-pod
spec:
  containers:
    - name: alpine
      image: alpine
      volumeMounts:
        - mountPath: /var/log
          name: local-vol
      command: ["touch"]
      args:
        - "name.txt"
  volumes:
    - name: local-vol
      persistentVolumeClaim:
        claimName: local-pvc
